services:
  api:
    container_name: api
    build:
      context: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/src:/src
  web:
    container_name: web
    build:
      context: frontend
    ports:
      - 3000:3000
  db:
    container_name: db
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_
volumes:
  db_volume:

